services:
    newscoop_instagram_plugin.lifecyclesubscriber:
        class: Newscoop\InstagramPluginBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
            - @newscoop.scheduler
        tags:
            - { name: kernel.event_subscriber}

    newscoop_instagram_plugin.instagram_service:
        class: Newscoop\InstagramPluginBundle\Services\InstagramService
        arguments:
            - @service_container

    newscoop_instagram_plugin.configure_menu_listener:
        class: Newscoop\InstagramPluginBundle\EventListener\ConfigureMenuListener
        tags:
          - { name: kernel.event_listener, event: newscoop_newscoop.menu_configure, method: onMenuConfigure }
        arguments:
            - @translator
